/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neuralnetwork_;

import Jama.Matrix;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author anshal
 */
public class CurvePanel extends javax.swing.JPanel {

    /**
     * Creates new form CurvePanel
     */
    ArrayList<Matrix> X=new ArrayList<Matrix>();
    ArrayList<Matrix> Y=new ArrayList<Matrix>();
    public CurvePanel(ArrayList<Matrix> X,ArrayList<Matrix> Y){
        this.X=X;
        this.Y=Y;
        this.setSize(550,550);
    }
    @Override
    public void paint(Graphics g){
        g.setColor(Color.black);
        g.fillRect(0, 0,550,550);
        g.setColor(Color.WHITE);
        g.drawLine(10,0,10,520);
        g.drawLine(0,510,520,510);
        for(int i=0;i<X.size();i++){
            int x=(int)X.get(i).get(1,0);
            int y=(int)X.get(i).get(2,0);
            x+=500;
            y+=500;
            x/=2;
            y/=2;
            if(Y.get(i).get(0,0)>0.5){
                g.setColor(Color.RED);
            }
            else
                g.setColor(Color.GREEN);
            g.drawLine(x, y, x, y);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(92, 231, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
